#pragma once

#include "guiAreaBase.hpp"

class GUIAreaProduct : public GUIAreaBase {
    enumVals lang_codes_enum{
        {"English", 0},
        {"Afar", 1},
        {"Abkhazian", 2},
        {"Afrikaans", 3},
        {"Amharic", 4},
        {"Arabic", 5},
        {"Assamese", 6},
        {"Aymara", 7},
        {"Azerbaijani", 8},
        {"Bashkir", 9},
        {"Byelorussian", 10},
        {"Bulgarian", 11},
        {"Bihari", 12},
        {"Bislama", 13},
        {"Bengali", 14},
        {"Tibetan", 15},
        {"Breton", 16},
        {"Catalan", 17},
        {"Corsican ", 18},
        {"Czech", 19},
        {"Welsh", 20},
        {"danish", 21},
        {"german", 22},
        {"Bhutani", 23},
        {"Greek", 24},
        {"English", 25},
        {"Esperanto", 26},
        {"Spanish", 27},
        {"Estonian", 28},
        {"Basque", 29},
        {"Persian", 30},
        {"Finnish", 31},
        {"Fiji", 32},
        {"Faeroese", 33},
        {"French", 34},
        {"Frisian", 35},
        {"Irish ", 36},
        {"Scots Gaelic", 37},
        {"Galician", 38},
        {"Guarani", 39},
        {"Gujarati", 40},
        {"Hausa", 41},
        {"Hindi", 42},
        {"Croatian", 43},
        {"Hungarian", 44},
        {"Armenian", 45},
        {"Interlingua", 46},
        {"Interlingue", 47},
        {"Inupiak", 48},
        {"Indonesian", 49},
        {"Icelandic", 50},
        {"Italian", 51},
        {"Hebrew", 52},
        {"Japanese", 53},
        {"Yiddish", 54},
        {"Javanese", 55},
        {"Georgian", 56},
        {"Kazakh", 57},
        {"Greenlandic", 58},
        {"Cambodian", 59},
        {"Kannada", 60},
        {"Korean", 61},
        {"Kashmiri", 62},
        {"Kurdish", 63},
        {"Kirghiz", 64},
        {"Latin", 65},
        {"Lingala", 66},
        {"Laothian", 67},
        {"Lithuanian", 68},
        {"Latvian,", 69},
        {"Malagasy", 70},
        {"Maori", 71},
        {"Macedonian", 72},
        {"Malayalam", 73},
        {"Mongolian", 74},
        {"Moldavian", 75},
        {"Marathi", 76},
        {"Malay", 77},
        {"Maltese", 78},
        {"Burmese", 79},
        {"Nauru ", 80},
        {"Nepali", 81},
        {"Dutch", 82},
        {"Norwegian", 83},
        {"Occitan", 84},
        {"(Afan) Oromo", 85},
        {"Oriya", 86},
        {"Punjabi", 87},
        {"Polish", 88},
        {"Pashto, Pushto", 89},
        {"Portuguese", 90},
        {"Quechua", 91},
        {"Rhaeto-Romance", 92},
        {"Kirundi", 93},
        {"Romanian", 94},
        {"Russian", 95},
        {"Kinyarwanda", 96},
        {"Sanskrit", 97},
        {"Sindhi", 98},
        {"Sangro", 99},
        {"Serbo-Croatian", 100},
        {"Singhalese", 101},
        {"Slovak", 102},
        {"Slovenian", 103},
        {"Samoan", 104},
        {"Shona", 105},
        {"Somali", 106},
        {"Albanian", 107},
        {"Serbian", 108},
        {"Siswati", 109},
        {"Sesotho", 110},
        {"Sudanese", 111},
        {"Swedish", 112},
        {"Swahili", 113},
        {"Tamil", 114},
        {"Tegulu", 115},
        {"Tajik", 116},
        {"Thai", 117},
        {"Tigrinya", 118},
        {"Turkmen", 119},
        {"Tagalog", 120},
        {"Setswana", 121},
        {"Tonga ", 122},
        {"Turkish", 123},
        {"Tsonga", 124},
        {"Tatar", 125},
        {"Twi", 126},
        {"Ukrainian", 127},
        {"Urdu", 128},
        {"Uzbek", 129},
        {"Vietnamese", 130},
        {"Volapuk", 131},
        {"Wolof", 132},
        {"Xhosa", 133},
        {"Yoruba", 134},
        {"Chinese", 135},
        {"Zulu ", 136},
    };

  public:
    GUIAreaProduct();
};
